# PyTorch Tensor
1. Tensor
2. Random tensor
3. Zero / One tensor
4. arange
5. tensors-like
6. device, dtype, shape, requires_grad

## 1. Tensor
- PyTorch의 가장 기본적인 building block
- Tensor에는 ndim과 shape가 있는데 차이는 이렇다
    - ndim  = 말 그대로 dimension이 몇개인가. 따라서 ndim은 single scalar value이다
    - shape = 각각의 차원에 몇개의 하위 차원 요소가 들어가 있는가
    - 예를 들면 이렇다
        - scalar (0D)
            - ndim = 0 (하위 차원이 없다) shape = [] (하위 차원이 없다)
        - vector (1D)
            - 예: [1,2,3,4]
            - ndim = 1 (하위 차원은 scalar이고 scalar의 ndim = 0)
            - shape = [4] (scalar가 4개 들어가 있음)
        - matrix (2D)
            - 예: [[1,2],[3,4],[5,6]]
            - ndim = 2 (하위 차원은 vector이고 vector의 ndim = 1) 
            - shape = [3,2] (vector가 3개 있고 각 vector에는 scalar가 2개씩 들어가 있음)

- 주로 다음과 같이 variable name이 setting된다 (scalar, vector는 lowercase, matrix, tesnor는 uppercase를 많이 쓰는 모양?)
    - scalar : a
    - vector : y
    - matrix : Q
    - tensor : X

- dtype은 Tensor에 들어있는 scalar의 type을 결정한다. default는 torch.float32
    - dtype으로 지정도 가능 (아래 참조)

In [1]:
import torch

In [2]:
# Scalar
a = torch.tensor(1)
print(f'a.ndim = {a.ndim}    a.shape = {a.shape}')

# Vector (1D)
y1 = torch.tensor([1]) # Scalar와는 다르다!
print(f'y1.ndim = {y1.ndim}    y1.shape = {y1.shape}')

y2 = torch.tensor([1,2,3,4])
print(f'y2.ndim = {y2.ndim}    y2.shape = {y2.shape}')

a.ndim = 0    a.shape = torch.Size([])
y1.ndim = 1    y1.shape = torch.Size([1])
y2.ndim = 1    y2.shape = torch.Size([4])


In [3]:
# Matrix (2D)
Q1 = torch.tensor([[1]])
print(f'Q1.ndim = {Q1.ndim}    Q1.shape = {Q1.shape}')

Q2 = torch.tensor([[1,2],[3,4],[5,6]])
print(f'Q2.ndim = {Q2.ndim}    Q2.shape = {Q2.shape}')
for i, y in enumerate(Q2):
    print(f'[{i}] : {y}')

Q1.ndim = 2    Q1.shape = torch.Size([1, 1])
Q2.ndim = 2    Q2.shape = torch.Size([3, 2])
[0] : tensor([1, 2])
[1] : tensor([3, 4])
[2] : tensor([5, 6])


In [4]:
# Tensor (ND)
X1 = torch.tensor([[[1]]])
print(f'X1.ndim = {X1.ndim}    X1.shape = {X1.shape}')

X2 = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
print(f'X2.ndim = {X2.ndim}    X2.shape = {X2.shape}')
for i,d2 in enumerate(X2):
    print(f'[{i}] : {d2}')

X1.ndim = 3    X1.shape = torch.Size([1, 1, 1])
X2.ndim = 3    X2.shape = torch.Size([2, 2, 2])
[0] : tensor([[1, 2],
        [3, 4]])
[1] : tensor([[5, 6],
        [7, 8]])


In [5]:
# dtype
Q1 = torch.tensor([[1,2],[3,4]])
print(Q1)
print(Q1.dtype)

Q2 = torch.tensor([[1.0,2.0],[3.0,4.0]])
print(Q2)
print(Q2.dtype)

Q3 = torch.tensor([[1,2],[3,4]], dtype=torch.float16)
print(Q3)
print(Q3.dtype)

tensor([[1, 2],
        [3, 4]])
torch.int64
tensor([[1., 2.],
        [3., 4.]])
torch.float32
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float16)
torch.float16


## 2. Random Tensor
- torch.rand
    - uniform distribution on the interval `[0,1)` 을 만든다
    - 기본적으로 shape을 지정해 주면 됨
    - 더 자세한 것은 다음을 참고 : https://pytorch.org/docs/stable/generated/torch.rand.html

In [6]:
import torch

Q1 = torch.rand(3,3,3,3)
print(Q1)

Q2 = torch.rand(size=(4,4)) # size를 명시적으로 넣을 수도 있다. 안 넣으면 default로 위와 같이 행동함
print(Q2)

tensor([[[[0.4317, 0.5073, 0.8773],
          [0.2286, 0.5672, 0.4344],
          [0.8892, 0.6132, 0.0783]],

         [[0.3691, 0.3377, 0.8720],
          [0.8989, 0.8509, 0.1463],
          [0.5764, 0.1102, 0.3394]],

         [[0.1773, 0.3162, 0.6467],
          [0.1458, 0.8761, 0.9501],
          [0.9868, 0.3272, 0.4622]]],


        [[[0.8220, 0.3400, 0.4744],
          [0.9419, 0.1344, 0.9929],
          [0.7756, 0.6308, 0.2709]],

         [[0.5790, 0.0791, 0.7402],
          [0.5914, 0.3827, 0.2002],
          [0.8753, 0.8205, 0.6569]],

         [[0.4495, 0.5649, 0.1459],
          [0.6533, 0.9138, 0.1146],
          [0.5521, 0.9185, 0.4815]]],


        [[[0.0204, 0.1684, 0.5822],
          [0.0188, 0.1112, 0.1175],
          [0.7254, 0.0729, 0.7871]],

         [[0.2939, 0.1804, 0.6919],
          [0.5434, 0.5970, 0.6286],
          [0.3583, 0.6227, 0.8340]],

         [[0.2224, 0.1572, 0.4092],
          [0.2197, 0.6753, 0.2181],
          [0.3632, 0.3572, 0.9878]]]])
tenso

## 3. Zeros and Ones
- (토막상식) Zeroes가 아님
    - Noun Zero의 plural form은 Zeros임
    - "to zero"할 때의 zero, 즉 verb인 zero의 3인칭 단수 가 zeroes임

In [7]:
Qz1 = torch.zeros(size=(4,4))
Qz2 = torch.zeros(3,3)

print(Qz1)
print(Qz2)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [8]:
Qo1 = torch.ones(size=(4,4))
Qo2 = torch.ones(3,3)

print(Qo1)
print(Qo2)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


### 4. arange
- range 도 있는데 이걸 쓰면 deprecation warning이 뜬다
    - `torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end)`
    - 대략 range가 python의 range와는 달리 `[start,end]`로 작동하니 inconsistent해서 python과 consistent한 arange를 쓰자라는 이야기
- start, end, step을 정할 수 있음

In [9]:
print(torch.arange(0,10))
print(torch.arange(start=0, end=10))
print(torch.arange(start=0, end=20, step=2))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


## like
- rand_like, zeros_like, ones_like
- dtype도 똑같이 따라감

In [10]:
Q = torch.rand(size=(3,3))
print(Q)
print(Q.ndim, Q.shape, Q.dtype)

Qr = torch.rand_like(Q)
print(Qr)
print(Qr.ndim, Qr.shape, Qr.dtype)

Qz = torch.zeros_like(Q)
print(Qz)
print(Qz.ndim, Qz.shape, Qz.dtype)

Qo= torch.ones_like(Q)
print(Qo)
print(Qo.ndim, Qo.shape, Qo.dtype)

tensor([[0.9424, 0.6636, 0.1563],
        [0.5673, 0.7983, 0.2082],
        [0.7639, 0.8822, 0.8058]])
2 torch.Size([3, 3]) torch.float32
tensor([[0.2325, 0.6448, 0.9592],
        [0.7342, 0.0809, 0.0845],
        [0.4493, 0.0617, 0.2776]])
2 torch.Size([3, 3]) torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
2 torch.Size([3, 3]) torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
2 torch.Size([3, 3]) torch.float32


In [11]:
Q = torch.rand(size=(3,3), dtype=torch.float16)
print(Q)
print(Q.ndim, Q.shape, Q.dtype)

Qr = torch.rand_like(Q)
print(Qr)
print(Qr.ndim, Qr.shape, Qr.dtype)

Qz = torch.zeros_like(Q)
print(Qz)
print(Qz.ndim, Qz.shape, Qz.dtype)

Qo= torch.ones_like(Q)
print(Qo)
print(Qo.ndim, Qo.shape, Qo.dtype)

tensor([[0.4258, 0.7847, 0.7065],
        [0.6743, 0.9429, 0.6064],
        [0.9893, 0.6870, 0.0215]], dtype=torch.float16)
2 torch.Size([3, 3]) torch.float16
tensor([[0.8262, 0.9092, 0.6108],
        [0.1416, 0.9092, 0.1992],
        [0.2549, 0.0757, 0.0962]], dtype=torch.float16)
2 torch.Size([3, 3]) torch.float16
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
2 torch.Size([3, 3]) torch.float16
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)
2 torch.Size([3, 3]) torch.float16


## device, dtype, shape, requires_grad
- Tensor에서 가장 많이 겪는 문제 3가지는 이렇다
    - Tensor shape가 서로 안맞아서 연산이 안됨
    - dtype을 잘못 지정해서 너무 느림 / 너무 정확도가 낮음
        - 서로 다른 type을 가지고 operation을 할 때 형변환은 자동으로 해 주는 듯? C와 비슷하게 더 큰 타입 우선, float 우선으로 해 주는 듯
    - device를 잘못 지정해서 같이 연산이 안됨 / 너무 느림
- device는 기본 cpu다
    - `torch.set_default_device`를 사용하면 CUDA로 지정할 수 있다
- requires_grad
    - 이 Tensor에 대해 gradient를 track할 것인지 여부를 정하는 부분이다
    - keras에서는 gradient tape이나 trainable같은 bool을 조작했는데 여기서는 Tensor단위로 조작하는 구나

In [12]:
# Jupyter notebook을 restart하고 Run All해야 원래 의도대로 나옴

Q = torch.rand(size=(3,3))
print(Q.device) # cpu

Q = torch.rand(size=(3,3), device='cuda')
print(Q.device) # cuda

torch.set_default_device('cuda')
Q = torch.rand(size=(3,3))
print(Q.device) # cuda

cpu
cuda:0
cuda:0


In [13]:
Q1 = torch.rand(size=(3,3), dtype=torch.float16)
print(Q1)
Q2 = torch.rand(size=(3,3), dtype=torch.float32)
print(Q2)

Q3 = Q1 * Q2

print(Q3)
print(Q3.dtype) # C처럼 자동으로 더 큰 타입으로 바꿔줌

tensor([[0.5229, 0.6592, 0.0643],
        [0.2134, 0.1534, 0.5308],
        [0.7588, 0.9341, 0.5630]], device='cuda:0', dtype=torch.float16)
tensor([[0.9879, 0.9446, 0.2228],
        [0.5277, 0.0601, 0.7846],
        [0.8423, 0.2141, 0.8168]], device='cuda:0')
tensor([[0.5166, 0.6227, 0.0143],
        [0.1126, 0.0092, 0.4164],
        [0.6391, 0.2000, 0.4599]], device='cuda:0')
torch.float32
