# PyTorch Tensor
1. Tensor
2. Random tensor
3. Zero / One tensor
4. arange
5. tensors-like
6. device, dtype, shape, requires_grad

## 1. Tensor
- PyTorch의 가장 기본적인 building block
- Tensor에는 ndim과 shape가 있는데 차이는 이렇다
    - ndim  = 말 그대로 dimension이 몇개인가. 따라서 ndim은 single scalar value이다
    - shape = 각각의 차원에 몇개의 하위 차원 요소가 들어가 있는가
    - 예를 들면 이렇다
        - scalar (0D)
            - ndim = 0 (하위 차원이 없다) shape = [] (하위 차원이 없다)
        - vector (1D)
            - 예: [1,2,3,4]
            - ndim = 1 (하위 차원은 scalar이고 scalar의 ndim = 0)
            - shape = [4] (scalar가 4개 들어가 있음)
        - matrix (2D)
            - 예: [[1,2],[3,4],[5,6]]
            - ndim = 2 (하위 차원은 vector이고 vector의 ndim = 1) 
            - shape = [3,2] (vector가 3개 있고 각 vector에는 scalar가 2개씩 들어가 있음)

- 주로 다음과 같이 variable name이 setting된다 (scalar, vector는 lowercase, matrix, tesnor는 uppercase를 많이 쓰는 모양?)
    - scalar : a
    - vector : y
    - matrix : Q
    - tensor : X

- dtype은 Tensor에 들어있는 scalar의 type을 결정한다. default는 torch.float32
    - dtype으로 지정도 가능 (아래 참조)

In [2]:
import torch

In [3]:
# Scalar
a = torch.tensor(1)
print(f'a.ndim = {a.ndim}    a.shape = {a.shape}')

# Vector (1D)
y1 = torch.tensor([1]) # Scalar와는 다르다!
print(f'y1.ndim = {y1.ndim}    y1.shape = {y1.shape}')

y2 = torch.tensor([1,2,3,4])
print(f'y2.ndim = {y2.ndim}    y2.shape = {y2.shape}')

a.ndim = 0    a.shape = torch.Size([])
y1.ndim = 1    y1.shape = torch.Size([1])
y2.ndim = 1    y2.shape = torch.Size([4])


In [4]:
# Matrix (2D)
Q1 = torch.tensor([[1]])
print(f'Q1.ndim = {Q1.ndim}    Q1.shape = {Q1.shape}')

Q2 = torch.tensor([[1,2],[3,4],[5,6]])
print(f'Q2.ndim = {Q2.ndim}    Q2.shape = {Q2.shape}')
for i, y in enumerate(Q2):
    print(f'[{i}] : {y}')

Q1.ndim = 2    Q1.shape = torch.Size([1, 1])
Q2.ndim = 2    Q2.shape = torch.Size([3, 2])
[0] : tensor([1, 2])
[1] : tensor([3, 4])
[2] : tensor([5, 6])


In [5]:
# Tensor (ND)
X1 = torch.tensor([[[1]]])
print(f'X1.ndim = {X1.ndim}    X1.shape = {X1.shape}')

X2 = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
print(f'X2.ndim = {X2.ndim}    X2.shape = {X2.shape}')
for i,d2 in enumerate(X2):
    print(f'[{i}] : {d2}')

X1.ndim = 3    X1.shape = torch.Size([1, 1, 1])
X2.ndim = 3    X2.shape = torch.Size([2, 2, 2])
[0] : tensor([[1, 2],
        [3, 4]])
[1] : tensor([[5, 6],
        [7, 8]])


In [6]:
# dtype
Q1 = torch.tensor([[1,2],[3,4]])
print(Q1)
print(Q1.dtype)

Q2 = torch.tensor([[1.0,2.0],[3.0,4.0]])
print(Q2)
print(Q2.dtype)

Q3 = torch.tensor([[1,2],[3,4]], dtype=torch.float16)
print(Q3)
print(Q3.dtype)

tensor([[1, 2],
        [3, 4]])
torch.int64
tensor([[1., 2.],
        [3., 4.]])
torch.float32
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float16)
torch.float16


## 2. Random Tensor
- torch.rand
    - uniform distribution on the interval `[0,1)` 을 만든다
    - 기본적으로 shape을 지정해 주면 됨
    - 더 자세한 것은 다음을 참고 : https://pytorch.org/docs/stable/generated/torch.rand.html

In [7]:
import torch

Q1 = torch.rand(3,3,3,3)
print(Q1)

Q2 = torch.rand(size=(4,4)) # size를 명시적으로 넣을 수도 있다. 안 넣으면 default로 위와 같이 행동함
print(Q2)

tensor([[[[0.7307, 0.4293, 0.1546],
          [0.0594, 0.5691, 0.4507],
          [0.3859, 0.7255, 0.0970]],

         [[0.2026, 0.3824, 0.0188],
          [0.0123, 0.6303, 0.1415],
          [0.0778, 0.8893, 0.0672]],

         [[0.8131, 0.2966, 0.9802],
          [0.1207, 0.1153, 0.4635],
          [0.3427, 0.2692, 0.9562]]],


        [[[0.0842, 0.8079, 0.6057],
          [0.8725, 0.1093, 0.2645],
          [0.5275, 0.1450, 0.4379]],

         [[0.1625, 0.0748, 0.4836],
          [0.3930, 0.5092, 0.0191],
          [0.3907, 0.0197, 0.7863]],

         [[0.6305, 0.5263, 0.3548],
          [0.4003, 0.8355, 0.1982],
          [0.5727, 0.2624, 0.3441]]],


        [[[0.0928, 0.5163, 0.5379],
          [0.5936, 0.8886, 0.9892],
          [0.5191, 0.5042, 0.6203]],

         [[0.2820, 0.6489, 0.6790],
          [0.7387, 0.9260, 0.1924],
          [0.9359, 0.9771, 0.8868]],

         [[0.6472, 0.7613, 0.0555],
          [0.0541, 0.9731, 0.8207],
          [0.6058, 0.1365, 0.6433]]]])
tenso

## 3. Zeros and Ones
- (토막상식) Zeroes가 아님
    - Noun Zero의 plural form은 Zeros임
    - "to zero"할 때의 zero, 즉 verb인 zero의 3인칭 단수 가 zeroes임

In [8]:
Qz1 = torch.zeros(size=(4,4))
Qz2 = torch.zeros(3,3)

print(Qz1)
print(Qz2)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [9]:
Qo1 = torch.ones(size=(4,4))
Qo2 = torch.ones(3,3)

print(Qo1)
print(Qo2)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


### 4. arange
- range 도 있는데 이걸 쓰면 deprecation warning이 뜬다
    - `torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end)`
    - 대략 range가 python의 range와는 달리 `[start,end]`로 작동하니 inconsistent해서 python과 consistent한 arange를 쓰자라는 이야기
- start, end, step을 정할 수 있음

In [10]:
print(torch.arange(0,10))
print(torch.arange(start=0, end=10))
print(torch.arange(start=0, end=20, step=2))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


## like
- rand_like, zeros_like, ones_like
- dtype도 똑같이 따라감

In [11]:
Q = torch.rand(size=(3,3))
print(Q)
print(Q.ndim, Q.shape, Q.dtype)

Qr = torch.rand_like(Q)
print(Qr)
print(Qr.ndim, Qr.shape, Qr.dtype)

Qz = torch.zeros_like(Q)
print(Qz)
print(Qz.ndim, Qz.shape, Qz.dtype)

Qo= torch.ones_like(Q)
print(Qo)
print(Qo.ndim, Qo.shape, Qo.dtype)

tensor([[0.8417, 0.4414, 0.6084],
        [0.4815, 0.1128, 0.5580],
        [0.9749, 0.7092, 0.4462]])
2 torch.Size([3, 3]) torch.float32
tensor([[0.5684, 0.2741, 0.2067],
        [0.8094, 0.2238, 0.7968],
        [0.9620, 0.1008, 0.3497]])
2 torch.Size([3, 3]) torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
2 torch.Size([3, 3]) torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
2 torch.Size([3, 3]) torch.float32


In [12]:
Q = torch.rand(size=(3,3), dtype=torch.float16)
print(Q)
print(Q.ndim, Q.shape, Q.dtype)

Qr = torch.rand_like(Q)
print(Qr)
print(Qr.ndim, Qr.shape, Qr.dtype)

Qz = torch.zeros_like(Q)
print(Qz)
print(Qz.ndim, Qz.shape, Qz.dtype)

Qo= torch.ones_like(Q)
print(Qo)
print(Qo.ndim, Qo.shape, Qo.dtype)

tensor([[0.3271, 0.2192, 0.6294],
        [0.6172, 0.2363, 0.8735],
        [0.3789, 0.4126, 0.4844]], dtype=torch.float16)
2 torch.Size([3, 3]) torch.float16
tensor([[0.6650, 0.0210, 0.5049],
        [0.8042, 0.8096, 0.7529],
        [0.3872, 0.2222, 0.7188]], dtype=torch.float16)
2 torch.Size([3, 3]) torch.float16
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
2 torch.Size([3, 3]) torch.float16
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)
2 torch.Size([3, 3]) torch.float16


## device, dtype, shape, requires_grad
- Tensor에서 가장 많이 겪는 문제 3가지는 이렇다
    - Tensor shape가 서로 안맞아서 연산이 안됨
    - dtype을 잘못 지정해서 서로 안맞아 연산이 안됨 / 너무 느림 / 너무 정확도가 낮음
    - device를 잘못 지정해서 같이 연산이 안됨 / 너무 느림

- device는 기본 cpu다
    - `torch.set_default_device`를 사용하면 CUDA로 지정할 수 있다

- requires_grad
    - 이 Tensor에 대해 gradient를 track할 것인지 여부를 정하는 부분이다
    - keras에서는 gradient tape이나 trainable같은 bool을 조작했는데 여기서는 Tensor단위로 조작하는 구나

In [13]:
# Jupyter notebook을 restart하고 Run All해야 원래 의도대로 나옴

Q = torch.rand(size=(3,3))
print(Q.device) # cpu

Q = torch.rand(size=(3,3), device='cuda')
print(Q.device) # cuda

torch.set_default_device('cuda')
Q = torch.rand(size=(3,3))
print(Q.device) # cuda

cpu
cuda:0
cuda:0


In [14]:
Q1 = torch.rand(size=(3,3), dtype=torch.float16)
print(Q1)
Q2 = torch.rand(size=(3,3), dtype=torch.float32)
print(Q2)

Q3 = Q1 * Q2

print(Q3)
print(Q3.dtype) # C처럼 자동으로 더 큰 타입으로 바꿔줌

tensor([[0.8936, 0.6880, 0.4453],
        [0.0473, 0.2778, 0.5786],
        [0.0462, 0.9028, 0.7998]], device='cuda:0', dtype=torch.float16)
tensor([[0.7575, 0.6125, 0.1070],
        [0.4004, 0.2287, 0.3689],
        [0.3049, 0.7245, 0.3035]], device='cuda:0')
tensor([[0.6769, 0.4214, 0.0477],
        [0.0190, 0.0636, 0.2135],
        [0.0141, 0.6541, 0.2427]], device='cuda:0')
torch.float32
