## Tensor basic operations
- Addition (+)
- Subtraction (-)
- Division (/,//)
    - python과 마찬가지로 float division인 `/`와 integer division인 `//`가 나뉘어 구현되어 있다
- Element-wise multiplication (*)
    - Tensor의 각각의 값을 특정 scalar와 곱한다
    - 또는 두 Tensor의 같은 위치에 있는 각각의 element를 서로 곱한다 (아래 코드 참조)
- Matrix multiplication (@)
    - 두 vector (1-dim)에 대해 하면 dot product를 해준다
    - 그외의 경우엔 서로 shape이 맞아야 (NxM,MxN) 해준다
    - matmul, mm 으로도 같은걸 할 수 있음
    - `.transpose`,`.t`,`.T`로 transpose도 할 수 있다

In [1]:
import torch

In [2]:
print('<Addition>')

X1 = torch.rand(2,2,2)
print('X1')
print(X1)

print('X1 + 10')
X1 = X1 + 10
print(X1)

<Addition>
X1
tensor([[[0.9527, 0.6189],
         [0.5519, 0.3559]],

        [[0.9320, 0.1105],
         [0.0672, 0.7335]]])
X1 + 10
tensor([[[10.9527, 10.6189],
         [10.5519, 10.3559]],

        [[10.9320, 10.1105],
         [10.0672, 10.7335]]])


In [3]:
print('<Subtraction>')

X1 = torch.rand(2,2,2)
print('X1')
print(X1)

print('X1 - 1')
X1 = X1 - 1
print(X1)

<Subtraction>
X1
tensor([[[0.8646, 0.5822],
         [0.4823, 0.5258]],

        [[0.2733, 0.1181],
         [0.7894, 0.2092]]])
X1 - 1
tensor([[[-0.1354, -0.4178],
         [-0.5177, -0.4742]],

        [[-0.7267, -0.8819],
         [-0.2106, -0.7908]]])


In [4]:
print('<Division>')

X1 = torch.rand(2,2,2)
print('X1')
print(X1)

print('X1 / 10')
X1 = X1 / 10
print(X1)
print()

y1 = torch.tensor([11,12,13])
print(f'y1 : {y1}')
print(f'y1 / 10 : {y1 / 10}')
print(f'y1 // 10 : {y1 // 10}')


<Division>
X1
tensor([[[0.1428, 0.9903],
         [0.0317, 0.0202]],

        [[0.5242, 0.3070],
         [0.2231, 0.5632]]])
X1 / 10
tensor([[[0.0143, 0.0990],
         [0.0032, 0.0020]],

        [[0.0524, 0.0307],
         [0.0223, 0.0563]]])

y1 : tensor([11, 12, 13])
y1 / 10 : tensor([1.1000, 1.2000, 1.3000])
y1 // 10 : tensor([1, 1, 1])


In [5]:
print('<Element-wise multiplication>')
print('<Multiply by scalar>')
X1 = torch.rand(2,2,2)
print('X1')
print(X1)

print('X1 * 10')
X1 = X1 * 10
print(X1)
print()

print('<Multiply by vector>')
X2 = torch.tensor([1,2,3])
X3 = torch.tensor([3,4,5])
print(f'X2: {X2}')
print(f'X3: {X3}')
print(f'X2 * X3: {X2 * X3}')

<Element-wise multiplication>
<Multiply by scalar>
X1
tensor([[[0.8787, 0.5548],
         [0.5444, 0.6892]],

        [[0.5520, 0.0397],
         [0.1061, 0.9507]]])
X1 * 10
tensor([[[8.7865, 5.5476],
         [5.4441, 6.8919]],

        [[5.5205, 0.3969],
         [1.0610, 9.5066]]])

<Multiply by vector>
X2: tensor([1, 2, 3])
X3: tensor([3, 4, 5])
X2 * X3: tensor([ 3,  8, 15])


In [6]:
print('<Matrix multiplication> (dot product)')
X1 = torch.rand(2,2)
print('X1')
print(X1)

X2 = torch.rand(2,2)
print('X2')
print(X2)

print('X1 @ X2')
X3 = X1 @ X2
print(X3)

print('where:')
print(f'\t{X1[0][0]:.4f}*{X2[0][0]:.4f} + {X1[0][1]:.4f}*{X2[1][0]:.4f} = {X1[0][0]*X2[0][0] + X1[0][1]*X2[1][0]:.4f}')
print()

print('- dot product of 2 vectors')
y1 = torch.tensor([1,2,3])
y2 = torch.tensor([3,4,5])
print(f'y1: {y1}')
print(f'y2: {y2}')
print(f'y1 @ y2: {y1 @ y2}')

<Matrix multiplication> (dot product)
X1
tensor([[0.7341, 0.5585],
        [0.0465, 0.5633]])
X2
tensor([[0.2650, 0.7138],
        [0.0730, 0.2322]])
X1 @ X2
tensor([[0.2353, 0.6537],
        [0.0535, 0.1640]])
where:
	0.7341*0.2650 + 0.5585*0.0730 = 0.2353

- dot product of 2 vectors
y1: tensor([1, 2, 3])
y2: tensor([3, 4, 5])
y1 @ y2: 26


In [8]:
# torch.matmul
X1 = torch.rand(2,2)
print('X1')
print(X1)

X2 = torch.rand(2,2)
print('X2')
print(X2)

print('torch.matmul(X1,X2)')
X3 = torch.matmul(X1, X2)
print(X3)

print('where:')
print(f'\t{X1[0][0]:.4f}*{X2[0][0]:.4f} + {X1[0][1]:.4f}*{X2[1][0]:.4f} = {X1[0][0]*X2[0][0] + X1[0][1]*X2[1][0]:.4f}')
print()

X1
tensor([[0.3924, 0.1745],
        [0.9665, 0.1564]])
X2
tensor([[0.6141, 0.4488],
        [0.8761, 0.4059]])
torch.matmul(X1,X2)
tensor([[0.3939, 0.2470],
        [0.7306, 0.4972]])
where:
	0.3924*0.6141 + 0.1745*0.8761 = 0.3939



In [9]:
# torch.mm
X1 = torch.rand(2,2)
print('X1')
print(X1)

X2 = torch.rand(2,2)
print('X2')
print(X2)

print('torch.mm(X1,X2)')
X3 = torch.mm(X1, X2)
print(X3)

print('where:')
print(f'\t{X1[0][0]:.4f}*{X2[0][0]:.4f} + {X1[0][1]:.4f}*{X2[1][0]:.4f} = {X1[0][0]*X2[0][0] + X1[0][1]*X2[1][0]:.4f}')
print()

X1
tensor([[0.0704, 0.8593],
        [0.1343, 0.3382]])
X2
tensor([[0.2065, 0.0426],
        [0.2471, 0.0582]])
torch.mm(X1,X2)
tensor([[0.2269, 0.0530],
        [0.1113, 0.0254]])
where:
	0.0704*0.2065 + 0.8593*0.2471 = 0.2269



In [14]:
# transpose

X1 = torch.rand(3,2)
print('X1')
print(X1)

# torch.transpose
# Returns a tensor that is a transposed version of input. The given dimensions dim0 and dim1 are swapped.
X1_t = X1.transpose(0,1)
print('X1.transpose')
print(X1_t)

# torch.t
# Expects input to be <= 2-D tensor and transposes dimensions 0 and 1.
X1_t = X1.t()
print('X1.t')
print(X1_t)

X1_t = X1.T
print('X1.T')
print(X1_t)

X1
tensor([[0.4150, 0.6268],
        [0.4554, 0.7195],
        [0.5823, 0.1356]])
X1.transpose
tensor([[0.4150, 0.4554, 0.5823],
        [0.6268, 0.7195, 0.1356]])
X1.t
tensor([[0.4150, 0.4554, 0.5823],
        [0.6268, 0.7195, 0.1356]])
X1.T
tensor([[0.4150, 0.4554, 0.5823],
        [0.6268, 0.7195, 0.1356]])


In [36]:
# mean, sum
X1 = torch.rand(3,2)
print('X1')
print(X1)

print('X1.mean()')
print(X1.mean())

print('X1.sum()')
print(X1.sum())

X1
tensor([[0.7290, 0.7775],
        [0.9486, 0.7516],
        [0.1811, 0.5962]])
X1.mean()
tensor(0.6640)
X1.sum()
tensor(3.9840)
