# Numpy Array

In [2]:
import numpy as np

arr_1d = np.array([1,2,3])
arr_2d = np.array([[1,2,3],[4,5,6]]) # 여기서 각각의 list는 하나의 row가 된다

print(arr_1d.shape)
print(arr_1d)
print(arr_2d.shape)
print(arr_2d)

(3,)
[1 2 3]
(2, 3)
[[1 2 3]
 [4 5 6]]


In [4]:
# numpy에서 index는 기본 row이다
print(arr_2d[0])
print(arr_2d[1])

[1 2 3]
[4 5 6]


In [5]:
arr_z = np.zeroes((4,5))
print(arr_z)
arr_zl = np.zeroes_like(arr_2d)
print(arr_zl)

arr_1 = np.ones((3,4))
print(arr_1)
arr_1l = np.ones_like(arr_2d)
print(arr_1l)


AttributeError: module 'numpy' has no attribute 'zeroes'