# Tensor shape operations

### reshape
- 말 그대로 Tensor의 shape을 바꾼다
- 새로운 Tensor를 return함
- Shape은 서로 element수가 일치해야 바꿀 수 있다

### view
- reshape와 비슷하지만 새로운 Tensor를 return하는게 아니라 기존의 Tensor를 다른 shape인것 '처럼' 다룰 수 있다는 것이 차이

### stack
- Tensor를 **새로운** dimension을 따라 concatenate한다. stack의 결과는 ndim이 1 늘어난다
    - dim을 설정해서 어느 dimension으로 concatenate할지 결정할 수 있다
    - dim은 `[0,ndim]` 범위에서 설정할 수 있다
- 예를들어 (4,3) Tensor A,B를 dim=0으로 stack한다면 (2,4,3) Tensor C가 나온다. 여기서 `C[0] = A`, `C[1] = B`가 되는 식

### cat
- Tensor를 **기존의** dimension을 따라 concatenate한다. cat의 결과는 ndim에 영향을 미치지 않는다
- cat할 Tensor들은 dim을 제외한 나머지 shape이 동일해야 한다
- 예를 들어 (M1,N,O) Tensor와 (M2,N,O) Tensor를 dim=0으로 cat한다면 결과 Tensor는 (M1+M2,N,O)가 되는 식이다

### squeeze
- size가 1인 차원을 삭제한다
- 예를 들어 shape이 $(A\times 1\times B\times 1\times C\times 1\times D)$ 인 Tensor가 있다면, squeeze를 거치고 나면 $(A\times B\times C\times D)$ 인 Tensor가 된다

### unsqueeze
- size가 1인 차원을 추가한다
- 예를 들어 shape이 (2,3)인 tensor에 unsqueeze(dim=1)을 한다면 결과 Tensor는 (2,1,3) 의 shape을 갖게 된다

### permute
- Tensor의 shape에서 dimension의 순서를 바꾼다
- 예를 들어 `X=torch.rand(2,3,4)`이고 `X.permute(2,1,0)`했다면 이렇게 하고 난 shape은 (4,3,2)가 된다

In [15]:
import torch
import traceback

In [16]:
# reshape

X = torch.rand(4,3)
print(X)

X_1 = X.reshape(2,6)
print(X_1)

tensor([[0.3437, 0.9468, 0.1185],
        [0.1438, 0.4045, 0.0123],
        [0.4066, 0.1774, 0.9209],
        [0.4258, 0.5916, 0.8720]])
tensor([[0.3437, 0.9468, 0.1185, 0.1438, 0.4045, 0.0123],
        [0.4066, 0.1774, 0.9209, 0.4258, 0.5916, 0.8720]])


In [17]:
# reshape시 size가 맞지 않으면 에러가 발생

X = torch.rand(4,3)

try:
    X_1 = X.reshape(2,5)
except:
    print(traceback.format_exc())

Traceback (most recent call last):
  File "/tmp/ipykernel_861175/3708386992.py", line 6, in <module>
    X_1 = X.reshape(2,5)
          ^^^^^^^^^^^^^^
RuntimeError: shape '[2, 5]' is invalid for input of size 12



In [18]:
# view

X = torch.rand(4,3)
print(X)

X_1 = X.view(2,6)
print(X_1)

print(f'set X[0][0] = 0.9999')
X[0][0] = 0.9999

print('X_1 after X[0][0] = 0.9999')
print(X_1) # X를 바꿨는데 X_1도 바뀜을 알 수 있다

tensor([[0.7058, 0.6062, 0.0911],
        [0.9869, 0.9567, 0.7165],
        [0.4913, 0.2403, 0.8323],
        [0.3492, 0.8693, 0.2930]])
tensor([[0.7058, 0.6062, 0.0911, 0.9869, 0.9567, 0.7165],
        [0.4913, 0.2403, 0.8323, 0.3492, 0.8693, 0.2930]])
set X[0][0] = 0.9999
X_1 after X[0][0] = 0.9999
tensor([[0.9999, 0.6062, 0.0911, 0.9869, 0.9567, 0.7165],
        [0.4913, 0.2403, 0.8323, 0.3492, 0.8693, 0.2930]])


In [19]:
# stack

X_1 = torch.rand(4,3)
X_2 = torch.rand(4,3)

print(f'X_1.shape: {X_1.shape}')
print(X_1)
print(f'X_2.shape: {X_2.shape}')
print(X_2)
print()

X_3 = torch.stack([X_1, X_2], dim=0)
print(f'X_3.shape: {X_3.shape}')
print(X_3)
print()

X_4 = torch.stack([X_1, X_2], dim=1)
print(f'X_4.shape: {X_4.shape}')
print(X_4)
print()


X_1.shape: torch.Size([4, 3])
tensor([[0.5928, 0.1042, 0.6848],
        [0.4948, 0.7186, 0.3037],
        [0.0940, 0.2967, 0.5056],
        [0.8616, 0.2199, 0.3155]])
X_2.shape: torch.Size([4, 3])
tensor([[0.8505, 0.2235, 0.0493],
        [0.5448, 0.7720, 0.6747],
        [0.8495, 0.5076, 0.4734],
        [0.8688, 0.9622, 0.0726]])

X_3.shape: torch.Size([2, 4, 3])
tensor([[[0.5928, 0.1042, 0.6848],
         [0.4948, 0.7186, 0.3037],
         [0.0940, 0.2967, 0.5056],
         [0.8616, 0.2199, 0.3155]],

        [[0.8505, 0.2235, 0.0493],
         [0.5448, 0.7720, 0.6747],
         [0.8495, 0.5076, 0.4734],
         [0.8688, 0.9622, 0.0726]]])

X_4.shape: torch.Size([4, 2, 3])
tensor([[[0.5928, 0.1042, 0.6848],
         [0.8505, 0.2235, 0.0493]],

        [[0.4948, 0.7186, 0.3037],
         [0.5448, 0.7720, 0.6747]],

        [[0.0940, 0.2967, 0.5056],
         [0.8495, 0.5076, 0.4734]],

        [[0.8616, 0.2199, 0.3155],
         [0.8688, 0.9622, 0.0726]]])



In [20]:
# cat

X_1 = torch.rand(4,3)
X_2 = torch.rand(4,3)

print(f'X_1.shape: {X_1.shape}')
print(X_1)
print(f'X_2.shape: {X_2.shape}')
print(X_2)
print()

X_3 = torch.cat([X_1, X_2], dim=0)
print(f'X_3.shape: {X_3.shape}')
print(X_3)
print()

X_4 = torch.cat([X_1, X_2], dim=1)
print(f'X_4.shape: {X_4.shape}')
print(X_4)
print()

X_1.shape: torch.Size([4, 3])
tensor([[0.7280, 0.8106, 0.4278],
        [0.8925, 0.7051, 0.8516],
        [0.9412, 0.1512, 0.1079],
        [0.8097, 0.0916, 0.3999]])
X_2.shape: torch.Size([4, 3])
tensor([[0.6464, 0.5965, 0.7494],
        [0.0806, 0.6003, 0.2211],
        [0.4949, 0.4382, 0.0830],
        [0.2313, 0.1890, 0.0511]])

X_3.shape: torch.Size([8, 3])
tensor([[0.7280, 0.8106, 0.4278],
        [0.8925, 0.7051, 0.8516],
        [0.9412, 0.1512, 0.1079],
        [0.8097, 0.0916, 0.3999],
        [0.6464, 0.5965, 0.7494],
        [0.0806, 0.6003, 0.2211],
        [0.4949, 0.4382, 0.0830],
        [0.2313, 0.1890, 0.0511]])

X_4.shape: torch.Size([4, 6])
tensor([[0.7280, 0.8106, 0.4278, 0.6464, 0.5965, 0.7494],
        [0.8925, 0.7051, 0.8516, 0.0806, 0.6003, 0.2211],
        [0.9412, 0.1512, 0.1079, 0.4949, 0.4382, 0.0830],
        [0.8097, 0.0916, 0.3999, 0.2313, 0.1890, 0.0511]])



In [21]:
# squeeze / unsqueeze

X1 = torch.rand(4,1,3,1,5)
print(f'X1.shape: {X1.shape}')
print(f'X1.squeeze().shape: {X1.squeeze().shape}')

X2 = torch.rand(2,3)
print(f'X2.shape: {X2.shape}')
print(f'X2.unsqueeze(dim=1).shape: {X2.unsqueeze(dim=1).shape}')


X1.shape: torch.Size([4, 1, 3, 1, 5])
X1.squeeze().shape: torch.Size([4, 3, 5])
X2.shape: torch.Size([2, 3])
X2.unsqueeze(dim=1).shape: torch.Size([2, 1, 3])


In [28]:
# permute

X = torch.tensor([[[1],[2]],[[3],[4]],[[5],[6]]])
print(f'X.shape: {X.shape}')
print(f'X:')
print(X)

X2 = X.permute(2,1,0)

# 대략 이렇게 바뀐다
#
#  [X[0][0][0], X[1][0][0], X[2][0][0]]
#  [X[0][1][0], X[1][1][0], X[2][1][0]]
#  

print(f'X2.shape: {X2.shape}')
print(f'X2:')
print(X2)


X.shape: torch.Size([3, 2, 1])
X:
tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])
X2.shape: torch.Size([1, 2, 3])
X2:
tensor([[[1, 3, 5],
         [2, 4, 6]]])
